TheAlgorithms/C-Sharp

- ciphers/vigenere_cipher.cs
- searches/linear_search.cs
I think I messed up my previous fork, but anyways this fork contains the vigenere cipher and linear search.
My implementation of the vigenere cipher might be flawed, feel free to change it by all means
> Add cipher - vigenere cipher

- other/prime_finder.cs
> Added PrimeTest

- sorts/bogosort.cs
> Added Bogosort

- sorts/heap_sort.cs
> Adds heap sort.

- sorts/quick_sort.cs
- sorts/radix_sort.cs
Simple quick sort algorithm
Contributes to #hacktoberfest for #1
> Added radix sort algorithm

- other/fermat_prime_checker.cs
Related to the issue #1 
https://en.wikipedia.org/wiki/Fermat_primality_test
> C# implementation of Fermat prime checker

- datastructure/BitArray/BitArray.cs
- datastructure/BitArray/TestBitArray.cs
I added a new directory (datastructure)  and a comprehensive BitArray.
> BitArray and new directory

- searches/AStar/Program.cs
My A* code was strangely formatted, so I went back and fixed it.
> Formatting

- ciphers/vigenere_cipher.cs
I improved the validation of the key (without for-loop) and put in some comments.
> improved the validation of the key and put in some comments

- data compression/huffman.cs
I changed the type of ```flag``` to type bool.  
```c#
bool flag = false;
```
> huffman.cs: changed flag type to bool

- data compression/huffman.cs
I fixed the method:  
```c#
public static Stack<Huff> GetSortedStack(IList<Huff> list)
```  
And put in some comments.
> huffman.cs : fixed method GetSortedStack(...)

- data compression/huffman.cs
I added properties for the classes Huff and Man:  
```c#
public string Data { get => data; set => data = value; }
public int Frequency { get => frequency; set => frequency = value; }
public Huff RightChild { get => rightChild; set => rightChild = value; }
public Huff LeftChild { get => leftChild; set => leftChild = value; }
```  
```c#
public List<string> Codec { get => codec; set => codec = value; }
public List<string> Data { get => data; set => data = value; }
```
> huffman.cs: added properties for the classes Huff and Man

- other/vowel_check.cs
I fixed the program. Changed the if-condition
> vowel_check: fixed bug

- strings/lcc.cs
- strings/palindrome.cs
added string folder for string manipulation algorithms. Added algorithms:
longest consecutive characters
palindrome
>  added string folder for string manipulation algorithms 

- ciphers/random cipher.cs
forgot to remove the part that i used this algorithm for!
> remove converting to hex and octal

- README.md
- sorts/binary_insertion_sort.cs
Added an implementation of the Binary Insertion Sort, and updated README.md to add links to both BIS and Random Cipher.
> Binary Insertion Sort

- README.md
- sorts/cocktail_sort.cs
Added cocktail_sort.cs and updated the README file.
> Adding Cocktail Sort

- traversals/tree_traversal.cs
This program traverses a tree from left to right at each level. The tree structure is randomly generated meaning that there is no set pattern as to how the levels and what element is placed at each position.
> Adding tree traversal

- Algorithms/Other/vowel_check.cs
> corrected vowels list

- DataStructures.Tests/BitArray/BitArrayTests.cs
- DataStructures/BitArray/BitArray.cs
Added new tests, refactored, organized and clean tests for BitArray Data structure.
> BitArray new tests

- DataStructures.Tests/BitArray/BitArrayTests.cs
- DataStructures/BitArray/BitArray.cs
Commenting on bit-array improved.
> Mods on bit-array data struct and added new tests.

- Algorithms.Tests/Sorters/CountingSorterTests.cs
- Algorithms/Sorters/CountingSorter.cs
> Add counting sort

- Algorithms/Numeric/Fibonacci.cs
- README.md
I added a Fibonacci sequence algorithm under "Algorithms/Numeric" and updated the README.md file to contain a reference to it
> Add Fibonacci sequence algorithm

- Algorithms.Tests/Search/LinearSearcherTests.cs
- Algorithms/Algorithms.csproj
- Algorithms/DataCompression/HuffmanCompressor.cs
- Algorithms/DataCompression/ShannonFanoCompressor.cs
- Algorithms/Search/LinearSearcher.cs
- C-Sharp.sln
- Utility/Exception/ItemNotFoundException.cs
- Utility/Extension/DictionaryExtension.cs
- Utility/Utility.csproj
Added few optimizations in the source. Here's the list:
- Handle nulls for `uncompressedText` in HuffmanCompressor & ShannonFanoCompressor.
- Move `ItemNotFoundException` to new Utility project so it can be reused. Update test cases.
- Move common `AddMany` methods to new Utility project and make it generic extension method.
> Code Optimizations

- .github/pull_request_template.md
Reword PR template to sound better
> Reword pull_request_template.md

- Algorithms.Tests/Sequences/NaturalSequenceTests.cs
- Algorithms/Sequences/NaturalSequence.cs
- README.md
> Add natural numbers sequence

- Algorithms/Search/FastSearcher.cs
Unit test fails sometimes because there were no bound checks.
> Add bound check to FastSearch

- .gitignore
- README.md
Added the working directory to the .gitignore, fixed markup to display correctly
> Improve Rider experience

- Algorithms.Tests/Numeric/Factorization/TrialDivisionFactorizerTests.cs
- Algorithms/Numeric/Factorization/IFactorizer.cs
- Algorithms/Numeric/Factorization/TrialDivisionFactorizer.cs
- README.md
> Add trial division factorization algorithm

- DataStructures.Tests/DoublyLinkedListTests.cs
- DataStructures/DoublyLinkedList/DoublyLinkedList.cs
- DataStructures/DoublyLinkedList/DoublyLinkedListNode.cs
- README.md
Added Doubly Linked List based on the list of the remaining data structures in #112.
Contains basic read, writes, deletes and finds. It also includes reverse functions (reverse the list and get a reversed enumerable) to showcase one of the benefits of doubly linked lists.
> Doubly linked list

- .travis.yml
- Algorithms.Tests/Algorithms.Tests.csproj
- Algorithms/Algorithms.csproj
- Algorithms/DataCompression/HuffmanCompressor.cs
- Algorithms/DataCompression/ShannonFanoCompressor.cs
- Algorithms/Search/AStar/AStar.cs
- Algorithms/Search/AStar/Node.cs
- DataStructures.Tests/BitArrayTests.cs
- DataStructures.Tests/DataStructures.Tests.csproj
- DataStructures/BitArray.cs
- DataStructures/DataStructures.csproj
- DataStructures/DoublyLinkedList/DoublyLinkedList.cs
- DataStructures/DoublyLinkedList/DoublyLinkedListNode.cs
- DataStructures/SinglyLinkedList/SinglyLinkedList.cs
- DataStructures/SinglyLinkedList/SinglyLinkedListNode.cs
- Utilities/Utilities.csproj
Enabled nullable context, updated targets for that, fixed emerged issues
> Enable nullable context in all projects

- DataStructures.Tests/ArrayBasedStackTests.cs
- DataStructures.Tests/ListBasedStackTests.cs
- DataStructures/ArrayBasedStack/ArrayBasedStack.cs
- DataStructures/ListBasedStack/ListBasedStack.cs
Added a list based stack and a array based stack based on the list of the remaining data structures in #112 .
Contains basic stack functions like peek, pop and push. Also able to count the elements inside the stack
> array and list based stack

- DataStructures.Tests/MinMaxHeapTests.cs
- DataStructures/MinMaxHeap.cs
- README.md
Added Min-Max heap, because it was in the list of data structures to be implemented.
Implementation is based on this Wikipedia article: https://en.wikipedia.org/wiki/Min-max_heap
> Add Min-Max heap

- README.md
> Add timeline to readme

- DataStructures/Timeline.cs
> Style changes in Timeline.cs

- Algorithms.Tests/Encoders/VigenereEncoderTests.cs
- Algorithms.Tests/Search/FastSearcherTests.cs
- Algorithms/Search/FastSearcher.cs
Add a couple of tests to definitely cover code paths that were not always covered by randomized tests
> Improve test coverage

- Algorithms.Tests/Sorters/External/ExternalMergeSorterTests.cs
- Algorithms/Sorters/External/ExternalMergeSorter.cs
- Algorithms/Sorters/External/IExternalSorter.cs
- Algorithms/Sorters/External/ISequentialStorage.cs
- Algorithms/Sorters/External/ISequentialStorageReader.cs
- Algorithms/Sorters/External/ISequentialStorageWriter.cs
- Algorithms/Sorters/External/Storages/IntFileStorage.cs
- Algorithms/Sorters/External/Storages/IntInMemoryStorage.cs
- README.md
- stylecop.ruleset
I've added an external version of the merge sort and all required for that plumbing.
> Add external merge sort

- Algorithms.Tests/Search/Substring/BoyerMoreTests.cs
- Algorithms/Search/Substring/BoyerMoore.cs
Hello,
I implemented the Boyer More Algorithm to find a pattern in a text.
I annouced it in #111.
> Boyer More Algorithm

- DataStructures.Tests/BinarySearchTreeTests.cs
- DataStructures/BinarySearchTree/BinarySearchTree.cs
- DataStructures/BinarySearchTree/BinarySearchTreeNode.cs
- README.md
Add an implementation of a binary search tree.
> Add Binary Search Tree Implementation

- Algorithms.Tests/Sorters/Comparison/CombSorterTests.cs
- Algorithms/Sorters/Comparison/CombSorter.cs
- README.md
Added an implementation of comb sort algorithm (variation on bubble sort). More info can be found here https://en.wikipedia.org/wiki/Comb_sort
> Add comb sorter

- Algorithms.Tests/Problems/StableMarriage/GaleShapleyTests.cs
- Algorithms/Problems/StableMarriage/Accepter.cs
- Algorithms/Problems/StableMarriage/GaleShapley.cs
- Algorithms/Problems/StableMarriage/Proposer.cs
- README.md
Hello,
I've implemented solution to Stable Marriage problem based on Gale–Shapley algorithm mentioned in #111.
> Stable Marriage problem and solution

- Algorithms/Other/Int2Binary.cs
- DataStructures/BitArray.cs
> Update use StringBuilder for concatenating strings

- Algorithms.Tests/Other/GeoLocationTests.cs
- Algorithms/Other/GeoLocation.cs
- C-Sharp.sln
- **Add an algorithm about Geolocation.**
> Add an algorithm about Geolocation.

- Algorithms.Tests/Numeric/PseudoInverse/PseudoInverseTests.cs
- Algorithms/Numeric/Pseudoinverse/PseudoInverse.cs
- README.md
- Utilities.Tests/Extensions/MatrixExtensionsTests.cs
- Utilities/Extensions/MatrixExtensions.cs
- Utilities/Extensions/VectorExtensions.cs
Added new algorithm for pseudo-inverse using moore-penrose algorithms and SVD.
> Open issue: numeric pseudo-inverse algorithm

- Algorithms.Tests/Numeric/EulerMethodTest.cs
- Algorithms/Numeric/EulerMethod.cs
- README.md
> Add Algorithm Euler method

- Algorithms/Other/Mandelbrot.cs
> Fix Mandelbrot parameter description

- CONTRIBUTING.md
> Mention target framework

- Algorithms.Tests/Numeric/Decomposition/SVDTests.cs
Svd_Random test was blinking (and it's still blinking, but much more rarely).
I also switched to using FluentAssertions for tests.
> Fix blinking test

- DIRECTORY.md
Convert relative links in DIRECTORY.md to absolute links. (This is needed for the website)
> Correct links in DIRECTORY.md

- Algorithms.Tests/Search/JumpSearcherTests.cs
- Algorithms/Search/JumpSearcher.cs
- DIRECTORY.md
- README.md
Hi, I have added the Jump Search algorithm and tests. Please have a look, and do let me know if there are any issues.
> Added Jump Search Algorithm

- DataStructures.Tests/SortedListTests.cs
- DataStructures/SortedList.cs
- README.md
I have added the Sorted List Data Structure implementation in C# using the binary search to find indices, required in #112.
The code is pretty simple thus the point 6 is not needed.
> Added Sorted List Data Structure

- DataStructures.Tests/DisjointSet/DisjointSetTests.cs
- DataStructures/DisjointSet/DisjointSet.cs
- DataStructures/DisjointSet/Node.cs
- README.md
I have added the Disjoint Set Data Structure implementation in C# using the Union By Rank and Path Compression heuristics.
> Added Disjoint Set Data Structure

- Algorithms.Tests/Sequences/ZeroSequenceTests.cs
- Algorithms/Sequences/ZeroSequence.cs
- README.md
> Add OEIS Zero sequence A000004

- DataStructures.Tests/Fenwick/BinaryIndexedTreeTests.cs
- DataStructures/Fenwick/BinaryIndexedTree.cs
- README.md
> Added Fenwick tree (aka Binary Indexed Tree)

- Algorithms.Tests/Graph/MinimumSpanningTree/KruskalTests.cs
- Algorithms/Graph/MinimumSpanningTree/Kruskal.cs
- README.md
Implemented Kruskal's algorithm to determine minimum spanning tree/forest of undirect graph.
https://en.wikipedia.org/wiki/Kruskal%27s_algorithm
> Kruskal's algorithm

- Algorithms.Tests/Algorithms.Tests.csproj
- Algorithms.Tests/Graph/Dijkstra/DijkstraTests.cs
- Algorithms/Algorithms.csproj
- Algorithms/Graph/Dijkstra/DijkstraAlgorithm.cs
- Algorithms/Graph/Dijkstra/DistanceModel.cs
- DataStructures/Graph/DirectedWeightedGraph.cs
- README.md
> Dijkstra algorithm implementation

- Algorithms.Tests/Numeric/MillerRabinPrimalityTest.cs
- Algorithms.Tests/Sequences/KolakoskiSequenceTests.cs
- Algorithms/Sequences/KolakoskiSequence2.cs
> Add recursive kolakoski sequence

- Algorithms.Tests/Sequences/CubesSequenceTests.cs
- Algorithms/Sequences/CubesSequence.cs
- README.md
Adding A000578 Cubes sequence.
[OEIS](https://oeis.org/A000578)
[Wikipedia](https://en.wikipedia.org/wiki/Cube_(algebra))
> Add A000578 Cubes sequence

- Algorithms.Tests/Sequences/NegativeIntegersSequenceTests.cs
- Algorithms/Sequences/NegativeIntegersSequence.cs
- README.md
Adding A001478 Negative Integers sequence
[OEIS](http://oeis.org/A001478)
[Wikipedia](https://wikipedia.org/wiki/Negative_number)
> Add A001478 Negative Integers sequence

- Algorithms.Tests/Graph/KosarajuTests.cs
- Algorithms/Graph/Kosaraju.cs
- README.md
Added Kosaraju algorithm to find SCC (strongly connected components) and test. 
Algorithm is explained in comments. Additionaly, there's a link on the summary of the class for furhter information.
> Added Kosaraju algorithm

- Algorithms.Tests/Numeric/MillerRabinPrimalityTest.cs
- Algorithms.Tests/Sorters/Comparison/TimSorterTests.cs
> Fix blinking test coverage

- Algorithms.Tests/Numeric/AmicableNumbersTest.cs
- Algorithms/Numeric/AmicableNumbersChecker.cs
- README.md
**[Amicable numbers](https://en.wikipedia.org/wiki/Amicable_numbers)** checker added.
> Amicable Numbers Checker

- README.md
- Add Discord and donate buttons.
> chore: add Discord and donate buttons

- Algorithms/Sorters/Comparison/InsertionSorter.cs
Changes `InsertionSorter.cs` implementation from Selection sort to Insertion sort
> Changes insertion sort implementation

- Algorithms/Algorithms.csproj
- Algorithms/Numeric/GaussJordanElimination.cs
- Algorithms/Search/BinarySearcher.cs
- Algorithms/Strings/Palindrome.cs
Updated documentation in areas with a TODO label.
> Documentation Updates

- .travis.yml
- Algorithms.Tests/Algorithms.Tests.csproj
- Algorithms/Algorithms.csproj
- CONTRIBUTING.md
- DataStructures.Tests/DataStructures.Tests.csproj
- DataStructures/DataStructures.csproj
- Utilities.Tests/Utilities.Tests.csproj
- Utilities/Utilities.csproj
> TargetFramework .net5.0 → .net6.0

- Algorithms.Tests/Strings/LevenshteinDistanceTests.cs
- Algorithms/Strings/LevenshteinDistance.cs
- README.md
Levenshtein Distance is used to calculate how many one character edits you need to perform to transform one word into another. Possible edit operations are: insertion, deletion, and substitution.
https://en.wikipedia.org/wiki/Levenshtein_distance
> Add Levenshtein Distance

- Algorithms.Tests/Strings/JaroSimilarityTests.cs
- Algorithms/Strings/JaroSimilarity.cs
- README.md
Jaro Similarity is used to measures how similar two strings are.
Wikipedia: https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance#Jaro_similarity.
> Add Jaro Similarity

- DataStructures/Stack/ArrayBasedStack.cs
This pull request is for issue #372. I did not add new tests because the changes do not implement a new feature, only remove an unnecessary structure to simplify the code
> remove unnecessary array loop

- Algorithms.Tests/Numeric/FactorialTests.cs
- Algorithms.Tests/Strings/PermutationTests.cs
- Algorithms/Numeric/Factorial.cs
- Algorithms/Numeric/Series/Maclaurin.cs
- [ x] I have performed a self-review of my code
- [ x] My code follows the style guidelines of this project
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] Comments in areas I changed are up to date
- [ x] I have added comments to hard-to-understand areas of my code
> Issue380 factorial with big integer

- Algorithms.Tests/Numeric/RungeKuttaMethodTest.cs
- Algorithms/Numeric/RungeKuttaMethod.cs
- README.md
I want to add implementation of Runge-Kutta (RK4) numeric method as it seems to be missing.
> Add Runge-Kutta method

- README.md
- [x ] I have performed a self-review of my code
- [ x] My code follows the style guidelines of this project
- [ x] I have made corresponding changes to the README.md
> Issue 398 ammendmend

- Algorithms.Tests/Algorithms.Tests.csproj
- DataStructures.Tests/DataStructures.Tests.csproj
- Utilities.Tests/Utilities.Tests.csproj
> Updated coverlet.collector to 6.0.0

- Algorithms.Tests/Algorithms.Tests.csproj
- DataStructures.Tests/DataStructures.Tests.csproj
- Utilities.Tests/Utilities.Tests.csproj
> Update Microsoft.NET.Test.Sdk to 17.8.0

- Algorithms.Tests/Numeric/FloorTests.cs
- Algorithms/Numeric/Floor.cs
- README.md
This pull request introduces the Floor algorithm, which performs the floor operation on a number. [Reference](https://en.wikipedia.org/wiki/Floor_and_ceiling_functions)
Similar to #490, I wanted to include this algorithm since it is present in other languages repositories, such as python.
> Add Floor numeric algorithm

- Algorithms.Tests/Numeric/PerfectCubeTests.cs
- Algorithms/Numeric/PerfectCubeChecker.cs
- README.md
This pull request introduces the Perfect Cube algorithm, which verifies if a number is a perfect cube. It has two different implementations, one using math and the other using binary search.
Similar to my previous contributions, I wanted to include this algorithm since it is present in other languages repositories, such as python.
> Add perfect cube numeric algorithm
