TheAlgorithms/C-Sharp

- numeric/binary_gcd.cs
Noticed that the Euclidean algorithm was implemented so I wanted to add the binary version as well.
For issue #1
> Add binary GCD algorithm

- Algorithms.Tests/Numeric/BinomialCoefficientTests.cs
- Algorithms.Tests/Numeric/FactorialTests.cs
- Algorithms/Numeric/BinomialCoefficient.cs
- Algorithms/Numeric/Factorial.cs
For factorial and binomial coefficient calculations.
> new numeric algorithms with new tests.

- Algorithms.Tests/Encoders/VigenereEncoderTests.cs
- Algorithms/Encoders/VigenereEncoder.cs
Fix intermittent bug where Travis build would hang unresponsive. This was due to incorrect handling of an empty key in VIgenere encoder
> Fix empty key bug in VigenereEncoder

- DataStructures.Tests/ArrayBasedStackTests.cs
- DataStructures/ArrayBasedStack/ArrayBasedStack.cs
As discussed in [here](https://github.com/TheAlgorithms/C-Sharp/pull/137#pullrequestreview-360866552) change the `ArrayBaseStack.cs` to not resizes on every PUSH so that it can be `O(1)`. The stack has now a Capacity which will double if it runs out of space.
> Change ArrayBaseStack to be O(1) for PUSH

- DataStructures.Tests/BinarySearchTreeTests.cs
- DataStructures/BinarySearchTree/BinarySearchTree.cs
- DataStructures/BinarySearchTree/BinarySearchTreeNode.cs
This change allows the implementation of BST to be a bit more flexible. This also makes it more consistent with other data structures such as Mix-Max Heap.
> Add ability for BST to use custom comparison function.

- DataStructures.Tests/ArrayBasedStackTests.cs
- DataStructures/ArrayBasedStack/ArrayBasedStack.cs
Fixed bugs in ArrayBasedStack implementation (ArrayBasedStack.cs)
- Renamed Count variable as Top to be in line with Stack's terminology
- Added code to check if stack is empty before performing Pop() or Peek()
> ArrayBasedStack - Fix bugs in Peek(), Pop() to show stack empty

- DIRECTORY.md
- README.md
- Fix the url for `Fibbonacci Heap` in rm.md and dir.md
- Change the urls of `Binary Search Tree` and `AA Tree` to a file instead of a folder for the website in dir.md
> Some small fixes to `DIRECTORY.md`

- DIRECTORY.md
The link was 
`https://github.com/TheAlgorithms/C-Sharp/blob/master/Algorithms/Search/AStar`
and now is
`https://github.com/TheAlgorithms/C-Sharp/blob/master/Algorithms/Search/AStar/AStar.cs`
This is only temporary and I know it is not really optimal because the algorithm is split into multiple files, but the website currently only works with a single file. The issue also occurs with other algorithms. Would it be possible to put everything important from one algorithm in one file @siriak or should I try to find another solution?
> Fix link for `A-Star` in `DIRECTORY.md`

- Algorithms/Search/AStar/PathfindingException.cs
- Utilities/Exceptions/ItemNotFoundException.cs
This PR replaces two uses of the `ApplicationException` class as a base class, using the `Exception` class instead.
This may seem tangential, but as this repository serves as a learning resource, I do believe that it should follow the best practices.
Using `ApplicationException` is not recommended. The [official documentation](https://learn.microsoft.com/en-us/dotnet/api/system.applicationexception?view=net-6.0) includes this remark:
> You should derive custom exceptions from the [Exception](https://learn.microsoft.com/en-us/dotnet/api/system.exception?view=net-6.0) class rather than the [ApplicationException](https://learn.microsoft.com/en-us/dotnet/api/system.applicationexception?view=net-6.0) class. You should not throw an [ApplicationException](https://learn.microsoft.com/en-us/dotnet/ …
> Remove uses of ApplicationException

- Algorithms.Tests/Strings/HammingDistanceTests.cs
- Algorithms/Strings/HammingDistance.cs
- README.md
Hamming distance between two [strings](https://en.wikipedia.org/wiki/String_(computer_science)) of equal length is the number of positions at which the corresponding [symbols](https://en.wikipedia.org/wiki/Symbol) are different. In other words, it measures the minimum number of substitutions required to change one string into the other, or the minimum number of errors that could have transformed one string into the other.
Wikipedia: https://en.wikipedia.org/wiki/Hamming_distance
> Add Hamming distance

- Algorithms.Tests/Sequences/CakeNumbersSequenceTests.cs
- Algorithms.Tests/Sequences/CentralPolygonalNumbersSequenceTests.cs
- Algorithms.Tests/Sequences/TetranacciNumbersSequenceTests.cs
- Algorithms.Tests/Sequences/TribonacciNumbersSequenceTests.cs
- Algorithms/Sequences/CakeNumbersSequence.cs
- Algorithms/Sequences/CentralPolygonalNumbersSequence.cs
- Algorithms/Sequences/TetranacciNumbersSequence.cs
- Algorithms/Sequences/TribonacciNumbersSequence.cs
- README.md
Issue #222: Add the implementation of the following OEIS to the repository:
- A000124 - Central Polygonal Numbers
- A000125 - Cake Numbers
- A000213 - Tribonacci Numbers
- A000288 - Tetranacci Numbers
> New OEIS sequences: A000124, A000125, A000213, A000288

- Algorithms.Tests/Other/SieveOfEratosthenesTests.cs
- Algorithms/Other/SieveOfEratosthenes.cs
- [ X] I have performed a self-review of my code
- [ X] My code follows the style guidelines of this project
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [ X] Comments in areas I changed are up to date
- [ X] I have added comments to hard-to-understand areas of my code
- [ X] I have made corresponding changes to the README.md
> Sieve of Eratosthenes.

- Algorithms.Tests/Encoders/BlowfishEncoderTests.cs
> Fix breaking BlowfishEncoder tests

- .github/workflows/ci.yml
- Algorithms.Tests/Algorithms.Tests.csproj
- Algorithms/Algorithms.csproj
- DataStructures.Tests/DataStructures.Tests.csproj
- DataStructures/DataStructures.csproj
- README.md
- Utilities.Tests/Utilities.Tests.csproj
- Utilities/Utilities.csproj
Migration to .NET 8:  .csproj files are being updated.
- \C-Sharp\Algorithms\Algorithms.csproj
- \C-Sharp\Algorithms.Tests\Algorithms.Tests.csproj
- \C-Sharp\DataStructures\DataStructures.csproj
- \C-Sharp\DataStructures.Tests\DataStructures.Tests.csproj
- \C-Sharp\Utilities\Utilities.csproj
- \C-Sharp\Utilities.Tests\Utilities.Tests.csproj
**Please let me know whether or not it would be necessary to create new unit tests for this change.**
Github issue #425: Proposed to migrate to .NET 8 to use the latest features of .NET ecosystem. It was requested to perform the changes in a few PRs to make them smaller and easier to review. This is the one only  meant to update .NET version.
> Migrate Project to .NET 8: Update Target Framework.

- Utilities.Tests/Extensions/DictionaryExtensionsTests.cs
- Utilities.Tests/Extensions/MatrixExtensionsTests.cs
- Utilities.Tests/Extensions/RandomExtensionsTests.cs
- Utilities.Tests/Extensions/VectorExtensionsTests.cs
- Utilities/Exceptions/ItemNotFoundException.cs
- Utilities/Extensions/DictionaryExtensions.cs
- Utilities/Extensions/MatrixExtensions.cs
- Utilities/Extensions/RandomExtensions.cs
- Utilities/Extensions/VectorExtensions.cs
Issue 425 - Migrate to DotNet 8
Github issue https://github.com/TheAlgorithms/C-Sharp/issues/425: Proposed to update to File-scoped namespaces. It was requested to perform the changes in a few PRs to make them smaller and easier to review. This is the one only meant to Switch to file-scoped namespaces.
> Project Utilities e UtilitiesTest Switch to file-scoped namespaces

- Algorithms/Encoders/FeistelCipher.cs
- DataStructures.Tests/LinkedList/LinkedListTests.cs
- DataStructures/LinkedList/SinglyLinkedList/SinglyLinkedList.cs
> added to Methods to the SinglyLinkedList (DeleteFirst, DeleteLast)

- DataStructures.Tests/Graph/DirectedWeightedGraphTests.cs
- DataStructures/Graph/DirectedWeightedGraph.cs
- DataStructures/Graph/Vertex.cs
DirectedWeightedGraph.RemoveVertex decrements the Count property, but keeps the index of vertex array and adjacency matrix. The inconsistent index and count cause issue when adding new vertex after removing vertex.
This PR resolves the issue and fixes #368.
> Fix inconsistent index and count when removing vertex from Graph.

- .github/workflows/ci.yml
Closes #453. Uses the same logic as in TheAlgorithms/Java#5100:
- the _tokenless_ upload is used for PRs from forks,
- the upload with token is used only for PRs and pushes within this repository.
Similar to TheAlgorithms/Rust#670.
> chore: upload coverage report using `CODECOV_TOKEN`

- Algorithms.Tests/Other/FloodFillTest.cs
- Algorithms.Tests/Other/KochSnowflakeTest.cs
- Algorithms.Tests/Other/MandelbrotTest.cs
- Algorithms/Algorithms.csproj
- Algorithms/Other/FloodFill.cs
- Algorithms/Other/KochSnowflake.cs
- Algorithms/Other/Mandelbrot.cs
[#441 Replace System.Drawing.Common](https://github.com/TheAlgorithms/C-Sharp/issues/441)
> Replace System.Drawing.Common

- Algorithms.Tests/Strings/Similarity/CosineSimilarityTests.cs
- Algorithms/Strings/Similarity/CosineSimilarity.cs
- README.md
This PR introduces an algorithm to calculate the Cosine Similarity between two strings. Cosine Similarity is a measure of similarity between two non-zero vectors of an inner product space. It is defined as the cosine of the angle between the vectors. This implementation allows us to determine how similar two strings are based on the frequency of their characters.
The Cosine Similarity algorithm works by representing each string as a vector of character frequencies, then calculating the cosine of the angle between these vectors. The steps involved are as follows:
1. Vector Representation: Convert each string into a vector where each element represents the frequency of a character in the string.
2. Dot Product Calculation: Compute the dot product of the two vectors.
3. Magnitude …
> Implementation of Cosine Similarity Algorithm for Strings

- Algorithms.Tests/Strings/Similarity/DamerauLevenshteinDistanceTests.cs
- Algorithms/Strings/Similarity/DamerauLevenshteinDistance.cs
- README.md
This PR introduces the implementation of the Damerau-Levenshtein distance algorithm. The Damerau-Levenshtein distance is a string metric for measuring the difference between two sequences. It is calculated as the minimum number of operations needed to transform one sequence into the other. The possible operations are insertion, deletion, substitution, and transposition.
The Damerau-Levenshtein distance algorithm calculates the number of single-character edits (insertions, deletions, substitutions, or transpositions) required to change one word into another. This implementation is efficient and uses dynamic programming to build a matrix of distances.
```
function DamerauLevenshteinDistance(string1, string2):
len1 = length of string1
len2 = length of string2
if len1 == 0:
return len2
if …
```
> Implementation of Damerau-Levenshtein Distance Algorithm

- CONTRIBUTING.md
Changed the `CONTRIBUTING.md` .NET version to match the version stated in `README.md`.
Closes #463
> Updating DOTNET version in CONTRIBUTING.md

- Algorithms.Tests/Numeric/AbsTests.cs
- Algorithms/Numeric/Abs.cs
- README.md
**Summary of the Change:**
This pull request introduces the Absolute algorithm, a simple and efficient way to calculate the absolute value of a number in C#.
**Motivation:**
I wanted to make my first Open Source contribution and noticed that the Absolute algorithm was implemented in other programming languages but not in C#, so I wanted to add this functionality to the project.
- [ X ] I have performed a self-review of my code
- [ X ] My code follows the style guidelines of this project
- [ X ] I have added tests that prove my fix is effective or that my feature works
- [ X ] New and existing unit tests pass locally with my changes
- [ X ] Comments in areas I changed are up to date
- [ X ] I have added comments to hard-to-understand areas of my code
- [ X ] I have made corresponding …
> Feature: Absolute value Algorithm

- Algorithms.Tests/Numeric/SoftMaxTests.cs
- Algorithms/Numeric/SoftMax.cs
- README.md
This pull request introduces an implementation of the SoftMax algorithm. The SoftMax function is often used as the last activation function of a neural network to normalize the output of a network to a probability distribution over predicted output classes.
The SoftMax function takes as input a vector z of K real numbers, and normalizes it into a probability distribution consisting of K probabilities proportional to the exponentials of the input numbers.
The SoftMax function is a critical component in many machine learning models, particularly in classification tasks within neural networks.
The time complexity for the SoftMax algorithm is `O(n)`, where n is the number of elements in the input array.
> Adding the SoftMax Function

- Algorithms.Tests/Strings/PatternMatching/WildCardMatcherTests.cs
- Algorithms/Strings/PatternMatching/WildCardMatcher.cs
- README.md
This pull request implements a wildcard pattern matching algorithm, providing regular expression matching with support for the `.` and `*` wildcard characters. The `.` matches any single character, while `*` matches zero or more of the preceding element. The matching covers the entire input string, ensuring it fully aligns with the pattern.
This feature offers a flexible and efficient way to perform pattern matching using basic wildcard characters, which is particularly useful in various text processing tasks.
The time complexity of the `WildCardMatcher` is `O(n*m)`, where `n` is the length of the input string and `m` is the length of the pattern.
> Feature: Wild Card Pattern Matching

- Algorithms.Tests/ModularArithmetic/ExtendedEuclideanAlgorithmTest.cs
- Algorithms/Algorithms.csproj
- Algorithms/DataCompression/BurrowsWheelerTransform.cs
- Algorithms/DataCompression/HuffmanCompressor.cs
- Algorithms/DataCompression/ShannonFanoCompressor.cs
- Algorithms/Encoders/NysiisEncoder.cs
- Algorithms/Graph/FloydWarshall.cs
- Algorithms/LinearAlgebra/Eigenvalue/PowerIteration.cs
- Algorithms/ModularArithmetic/ChineseRemainderTheorem.cs
- Algorithms/ModularArithmetic/ExtendedEuclideanAlgorithm.cs
- Algorithms/ModularArithmetic/ModularMultiplicativeInverse.cs
- Algorithms/Other/FloodFill.cs
- Algorithms/Other/GaussOptimization.cs
- Algorithms/Other/RGBHSVConversion.cs
- Algorithms/Search/FastSearcher.cs
- Algorithms/Sorters/Comparison/MergeSorter.cs
- Algorithms/Sorters/Comparison/TimSorter.cs
- Algorithms/Sorters/Comparison/TimSorterSettings.cs
- Algorithms/Sorters/Utils/GallopingStrategy.cs
- Algorithms/Strings/Similarity/CosineSimilarity.cs
- Algorithms/Strings/Similarity/DamerauLevenshteinDistance.cs
- DataStructures/AATree/AATree.cs
- DataStructures/DataStructures.csproj
- DataStructures/Graph/DirectedWeightedGraph.cs
- DataStructures/Hashing/HashTable.cs
- DataStructures/RedBlackTree/RedBlackTreeNode.cs
- DataStructures/ScapegoatTree/ScapegoatTree.cs
- Utilities/Extensions/DictionaryExtensions.cs
- Utilities/Utilities.csproj
This pull request updates **StyleCop.Analyzers** to version `1.2.0-beta.556` in the following projects:
- **Algorithms**
- **DataStructures**
- **Utilities**
The update to the beta version is necessary to support modern C# syntax, including nullable reference types and other new language features that are not recognized by earlier stable versions of StyleCop.
1. **StyleCop Update:**
- **StyleCop.Analyzers** has been updated from the previous version to `1.2.0-beta.556`, which includes support for modern C# syntax.
- This update resolves compatibility issues related to newer C# language features such as `?[]` (nullable arrays), default interface implementations, pattern matching enhancements, and more.
- The `1.2.0-beta` version is now compatible with newer syntax and is essential for …
> Update style cop

- Algorithms.Tests/Other/TriangulatorTests.cs
- Algorithms/Other/Triangulator.cs
- README.md
Implemented a triangulation algorithm to calculate your position based on distances from three base stations.
> Triangulation algorithms to find your location

- Algorithms.Tests/Numeric/CeilTests.cs
- Algorithms/Numeric/Ceil.cs
- README.md
This pull request introduces the `Ceil` algorithm, which performs the ceiling operation on a number. [Reference](https://en.wikipedia.org/wiki/Floor_and_ceiling_functions)
I wanted to include this algorithm since it is present in other languages repositories, such as python.
> Add Ceil numeric algorithm

- Algorithms.Tests/LinearAlgebra/Distances/ChebyshevTests.cs
- Algorithms/LinearAlgebra/Distances/Chebyshev.cs
- README.md
This pull request introduces the Chebyshev distance algorithm, where the distance between two points is the greatest of their differences along any coordinate dimension. [Source](https://en.wikipedia.org/wiki/Chebyshev_distance)
Similar to my previous contributions, I wanted to include this algorithm since it is present in other languages repositories, such as python.
> Add Chebyshev distance algorithm

- Algorithms.Tests/LinearAlgebra/Distances/MinkowskiTests.cs
- Algorithms/LinearAlgebra/Distances/Minkowski.cs
- README.md
This pull request introduces the Minkowski distance algorithm, which calculates the distance between two points in an N-dimensional space for a given order. The Minkowski distance generalizes both the Manhattan distance (order = 1) and the Euclidean distance (order = 2). It is defined as the p-th root of the sum of the absolute differences raised to the power of p between the coordinates of the points. [Source](https://en.wikipedia.org/wiki/Minkowski_distance)
Similar to my previous contributions, I wanted to include this algorithm since it is present in other language repositories, such as Python.
> Add Minkowski distance algorithm

- Algorithms.Tests/Graph/Dijkstra/DijkstraTests.cs
- Algorithms/Graph/Dijkstra/DijkstraAlgorithm.cs
SUMMARY
- The original implementation of Dijkstra algorithm can't go through vertices which have been counted previously. Add priority queue to fix it and modify the algorithm's test as well.
MOTIVATION
- The original implementation of the algorithm is weird. And then I found that issue #386 was not fixed but staled. So I fix it.
CONTENT
1. Add priority queue to track the previous counted vertices distances. Then we can find the minimal distance across all the possible vertices. 
2. Remove redundant calculations.
3. Modify the test cases.
> Fix Dijkstra algorithm implementation

- Algorithms.Tests/Search/FastSearcherTests.cs
Enhanced FastSearcherTests with additional test cases and improved assertions using FluentAssertions.
-         FindIndex_ItemPresentInArrayOfDuplicates_IndexCorrect: Verifies correct behavior when searching for an item in an array with all duplicate values.
-         FindIndex_ItemMissingInArrayOfDuplicates_ItemNotFoundExceptionThrown: Ensures an exception is thrown when searching for an absent item in an array of duplicates.
-         FindIndex_ItemOutOfRange_ItemNotFoundExceptionThrown: Confirms exceptions are raised for items smaller or larger than the array's range.
Improved readability.
Consistent assertion style.
Expressive exception validation using act.Should().Throw<Exception>().
Maintained edge case validation for empty arrays, out-of-range values, and general functionality. …
> Enhanced FastSearcherTests with additional test cases

- Algorithms.Tests/Sorters/Comparison/GnomeSorterTests.cs
- Algorithms/Sorters/Comparison/GnomeSorter.cs
- README.md
Summary of Change:
This pull request introduces the Gnome sort, which is a simple comparison-based sorting algorithm. It is simple, but educational.
> Add Gnome sort algorithm

- Algorithms.Tests/Encoders/AutokeyEncoderTests.cs
- Algorithms/Encoders/AutokeyEncorder.cs
- README.md
Summary of the Change:
This pull request introduces the Autokey cipher which is a type of polyalphabetic cipher. This cipher works by choosing a key then appending it to the plaintext to form an extended key.
> Add Autokey encoder

- Algorithms.Tests/Shufflers/RecursiveShufflerTests.cs
- Algorithms/Shufflers/RecursiveShuffler.cs
- README.md
Summary of the Change:
This pull request introduces Recursive shuffling algorithm which is a recursive version of Fisher-Yates shuffling algorithm. This can be used for educational purposes only due to stack depth limits.
> Add Recursive shuffling algorithm

- Algorithms/Numeric/AdditionWithoutArithmetic.cs
- Algorithms/Numeric/KrishnamurthyNumberChecker.cs
- Algorithms/Other/Geofence.cs
- Algorithms/Other/Geohash.cs
- Algorithms/Other/JulianEaster.cs
- Algorithms/Other/Triangulator.cs
- Algorithms/RecommenderSystem/ISimilarityCalculator.cs
- Algorithms/Shufflers/LINQShuffler.cs
- Algorithms/Shufflers/NaiveShuffler.cs
- Algorithms/Shufflers/RecursiveShuffler.cs
- Algorithms/Sorters/Comparison/BasicTimSorter.cs
- Algorithms/Sorters/Utils/GallopingStrategy.cs
- Algorithms/Stack/BalancedParenthesesChecker.cs
- Algorithms/Stack/NextGreaterElement.cs
- Algorithms/Stack/ReverseStack.cs
- DataStructures/Cache/LfuCache.cs
- DataStructures/Cache/LruCache.cs
- DataStructures/DisjointSet/DisjointSet.cs
- DataStructures/Hashing/Entry.cs
- DataStructures/Hashing/NumberTheory/PrimeNumber.cs
Summary of the change
This pull request contains the following changes
- Converted block-scoped namespaces to file-scoped namespaces for consistency
- Removed redundant/unused global using directives to improve code clarity
- Aligned code formatting with project conventions and C# 10+ style guidelines
Issue link: https://github.com/TheAlgorithms/C-Sharp/issues/520
> refactor: migrate to file-scoped namespaces and remove unused global usings statements

- DataStructures/AATree/AATree.cs
- DataStructures/AVLTree/AVLTree.cs
- DataStructures/BinarySearchTree/BinarySearchTree.cs
- DataStructures/RedBlackTree/RedBlackTree.cs
**Description**
This PR contains the following points:
- Replaced escaped quotes (\") with raw string literals ("""...""") in exception and log messages.
- Removed unnecessary escape sequences, making strings cleaner and easier to read.
**Issue link:** https://github.com/TheAlgorithms/C-Sharp/issues/520
> refactor(csharp): replace escaped quotes in interpolated strings with raw string literals for clarity

- DataStructures.Tests/Hashing/HashTableTests.cs
Just call resize with a negative key to trigger line 300 and actually improve the coverage
See issue #465
> Test HashTable.Resize() directly

- Algorithms.Tests/MachineLearning/LogisticRegressionTests.cs
- Algorithms/MachineLearning/LogisticRegression.cs
- README.md
Logistic Regression is a core algorithm in machine learning and is commonly used for binary classification problems. Adding this implementation increases the educational value and completeness of the repository for AI/ML learners.
> Add Logistic Regression Algorithm for Machine Learning
